/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_omniti_labs_jlog */

#ifndef _Included_com_omniti_labs_jlog
#define _Included_com_omniti_labs_jlog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_omniti_labs_jlog
 * Method:    jlog_ctx_new
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_omniti_labs_jlog_jlog_1ctx_1new
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_omniti_labs_jlog
 * Method:    jlog_ctx_close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_omniti_labs_jlog_jlog_1ctx_1close
  (JNIEnv *, jobject);

/*
 * Class:     com_omniti_labs_jlog
 * Method:    jlog_ctx_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_omniti_labs_jlog_jlog_1ctx_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_omniti_labs_jlog
 * Method:    raw_size
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_omniti_labs_jlog_raw_1size
  (JNIEnv *, jobject);

/*
 * Class:     com_omniti_labs_jlog
 * Method:    get_checkpoint
 * Signature: (Ljava/lang/String;)Lcom/omniti/labs/jlog/Id;
 */
JNIEXPORT jobject JNICALL Java_com_omniti_labs_jlog_get_1checkpoint
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_omniti_labs_jlog
 * Method:    list_subscribers
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_omniti_labs_jlog_list_1subscribers
  (JNIEnv *, jobject);

/*
 * Class:     com_omniti_labs_jlog
 * Method:    get_error
 * Signature: ()Lcom/omniti/labs/jlog/jlog_err;
 */
JNIEXPORT jobject JNICALL Java_com_omniti_labs_jlog_get_1error
  (JNIEnv *, jobject);

/*
 * Class:     com_omniti_labs_jlog
 * Method:    get_error_string
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_omniti_labs_jlog_get_1error_1string
  (JNIEnv *, jobject);

/*
 * Class:     com_omniti_labs_jlog
 * Method:    get_errno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_omniti_labs_jlog_get_1errno
  (JNIEnv *, jobject);

/*
 * Class:     com_omniti_labs_jlog
 * Method:    open_writer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_omniti_labs_jlog_open_1writer
  (JNIEnv *, jobject);

/*
 * Class:     com_omniti_labs_jlog
 * Method:    open_reader
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_omniti_labs_jlog_open_1reader
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_omniti_labs_jlog
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_omniti_labs_jlog_close
  (JNIEnv *, jobject);

/*
 * Class:     com_omniti_labs_jlog
 * Method:    alter_mode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_omniti_labs_jlog_alter_1mode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_omniti_labs_jlog
 * Method:    alter_journal_size
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_omniti_labs_jlog_alter_1journal_1size
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_omniti_labs_jlog
 * Method:    alter_safety
 * Signature: (Lcom/omniti/labs/jlog/jlog_safety;)V
 */
JNIEXPORT void JNICALL Java_com_omniti_labs_jlog_alter_1safety
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_omniti_labs_jlog
 * Method:    add_subscriber
 * Signature: (Ljava/lang/String;Lcom/omniti/labs/jlog/jlog_position;)V
 */
JNIEXPORT void JNICALL Java_com_omniti_labs_jlog_add_1subscriber
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_omniti_labs_jlog
 * Method:    remove_subscriber
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_omniti_labs_jlog_remove_1subscriber
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_omniti_labs_jlog
 * Method:    write
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_com_omniti_labs_jlog_write
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     com_omniti_labs_jlog
 * Method:    read_interval
 * Signature: ()Lcom/omniti/labs/jlog/Interval;
 */
JNIEXPORT jobject JNICALL Java_com_omniti_labs_jlog_read_1interval
  (JNIEnv *, jobject);

/*
 * Class:     com_omniti_labs_jlog
 * Method:    read
 * Signature: (Lcom/omniti/labs/jlog/Id;)Lcom/omniti/labs/jlog/Message;
 */
JNIEXPORT jobject JNICALL Java_com_omniti_labs_jlog_read
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_omniti_labs_jlog
 * Method:    read_checkpoint
 * Signature: (Lcom/omniti/labs/jlog/Id;)V
 */
JNIEXPORT void JNICALL Java_com_omniti_labs_jlog_read_1checkpoint
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_omniti_labs_jlog
 * Method:    advance
 * Signature: (Lcom/omniti/labs/jlog/Id;Lcom/omniti/labs/jlog/Id;Lcom/omniti/labs/jlog/Id;)Lcom/omniti/labs/jlog/Interval;
 */
JNIEXPORT jobject JNICALL Java_com_omniti_labs_jlog_advance
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_omniti_labs_jlog
 * Method:    first_log_id
 * Signature: (Lcom/omniti/labs/jlog/Id;)Lcom/omniti/labs/jlog/Id;
 */
JNIEXPORT jobject JNICALL Java_com_omniti_labs_jlog_first_1log_1id
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_omniti_labs_jlog
 * Method:    last_log_id
 * Signature: (Lcom/omniti/labs/jlog/Id;)Lcom/omniti/labs/jlog/Id;
 */
JNIEXPORT jobject JNICALL Java_com_omniti_labs_jlog_last_1log_1id
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
